// syscalls.h -- system call numbers shared with the kernel (keep in sync).
#pragma once
#define SYS_WRITE  0
#define SYS_GETPID 1
#define SYS_YIELD  2
#define SYS_SLEEP  3
#define SYS_EXIT   4
#define SYS_REPORT 5
#define SYS_OPEN   6
#define SYS_READ   7
#define SYS_CLOSE  8
#define SYS_FORK   9
#define SYS_READDIR 10
#define SYS_EXEC   11
#define SYS_WAIT   12
#define SYS_SBRK   13
#define SYS_MMAP   14
#define SYS_MUNMAP 15
#define SYS_SHM_CREATE 16
#define SYS_SHM_MAP    17
#define SYS_PIPE   18
#define SYS_DUP2   19
#define SYS_KILL   20
#define SYS_SIGNAL 21
#define SYS_SIGRETURN 22
#define SYS_PING   28
#define SYS_RESOLVE 29
#define SYS_SHUTDOWN 30
#define SYS_SOCKET   31
#define SYS_BIND     32
#define SYS_SENDTO   33
#define SYS_RECVFROM 34
#define SYS_CONNECT  35
#define SYS_LISTEN   36
#define SYS_ACCEPT   37
#define SYS_POLL     38
#define SYS_SOCKSHUT 39
#define SYS_INPUT_READ 40
#define SYS_GFX_ACQUIRE 41
#define SYS_GFX_FLUSH   42
#define SYS_SEAT_SWITCH 43
